# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: recent
on:
  schedule: [{cron: "0 16 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_output: png
          filename: recent.png
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          extras_css: "@import url(https://cdn.jsdelivr.net/gh/n0099/n0099@main/extras.css)"
          config_timezone: Asia/Shanghai
          repositories_skipped: open-tbclient, tbclient.protobuf

          base:

          plugin_activity: yes
          plugin_activity_days: 365
          plugin_activity_filter: all
          plugin_activity_limit: 30
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_activity_timestamps: yes

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_from: 1000
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_languages: yes
          plugin_languages_other: yes
          plugin_languages_sections: recently-used
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_analysis_timeout: 60
          plugin_languages_analysis_timeout_repositories: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 365
          plugin_languages_recent_load: 1000
          plugin_languages_threshold: 0%

          plugin_stars: yes
          plugin_stars_limit: 20
