# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: stackoverflow
on:
  schedule: [{cron: "0 16 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_output: png
          filename: stackoverflow.png
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          extras_css: "@import url(https://cdn.jsdelivr.net/gh/n0099/n0099@main/extras.css)"
          config_timezone: Asia/Shanghai
          config_display: large

          base:
          base_skip: yes

          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 12576620
          plugin_stackoverflow_limit: 30
          plugin_stackoverflow_lines: 5
          plugin_stackoverflow_lines_snippet: 5
          plugin_stackoverflow_sections: answers-recent
