# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: steam
on:
  schedule: [{cron: "0 16 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          config_output: png
          filename: steam.png
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          extras_css: "@import url(https://cdn.jsdelivr.net/gh/n0099/n0099@main/extras.css)"
          config_timezone: Asia/Shanghai

          base:
          base_skip: yes

          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: 76561198346434300
          plugin_steam_sections: recently-played
          plugin_steam_games_limit: 2
          plugin_steam_recent_games_limit: 2
          plugin_steam_achievements_limit: 2
